name: client 
on:
  push:
    paths:
      - .github/workflows/main.yml
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        
      - name: Cypress.io
        working-directory: client/cypress
      - uses: cypress-io/github-action@v2.9.7
        with:
          project: client
