name: client 
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v2.4.2
        
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          working-directory: client/
          start: npm run dev-all
